const pathObj = {
  loginUser: "/v1/admin/login",
  getUsers: "/v1/admin/user",
  userProfile: "/v1/user/profile",
  updateUser: "/v1/admin/user/edit",
  getSubAdmin: "v1/admin/subadmin",
  editSubAdmin: "v1/admin/subadmin",
  forgetPassword: "/v1/admin/forgot-password",
  resetPassword: "/v1/admin/reset-password",
  changePassword: "/v1/admin/change-password",
  userVerify: "/v1/admin/user/verify",
  editProfile: "/v1/admin/edit-profile",
  getStaticContent: "/v1/admin/static-content",
  updateSettings: "/v1/admin/setting",
  emailTemplate: "/v1/admin/email-template",
  emailStatus: "/v1/admin/email-template/change-status",
  notificationToggle: "/v1/admin/notification-toggle",
  changeContentStatus: "/v1/admin/static-content/change-status",
  getFAQs: "/v1/admin/faq",
  changeFAQStatus: "/v1/admin/faqs/status",
  reportAbuseListing: "v1/admin/report-abuse",
  changeStatus: "/v1/admin/change-status",
  verficationDetail: "v1/admin/user/verification-details",
  notifications: "v1/admin/notification",
  getSettings: "/v1/admin/setting",
  allNotificationUser: "/v1/admin/user/all-users",
};

export default pathObj;
