export const permissionsMap = Object.freeze({
  dashboard: "/dashboard",
  user_manager: "/users",
  // subAdmin_manager: "/sub-admin-manager",
  settings: "/setting",
  email_manager: "/email-manager",
  FAQ: "/faqs",
  game_type_manager: "/game-type-manager",
  how_to_play_manager: "/how-to-play-manager",
  banner_manager: "/banner-manager",
  trading_question_manager: "/trading-question-manager",
  notification_manager: "/notification_manager",
  offer_manager: "/offer-manager",
  player_card_manager: "/player-card-manager",
  subscribed_manager: "/subscribed-manager",
  achievement_and_badges: "/achievement-and-badges",
  challenges_manager: "/challenges-manager",
  community_moderator: "/community-moderator-manager",
  transaction_manager: "/transaction-manager",
  static_pages_management: "/static-content",
  widthDrawal_request_manager: "/withdrawal-request-manager",
  feedback_manager: "/feedback-manager",
});
