const Permission = [
 
  {
    manager: "users_managers",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "transaction_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "subAdmin_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "reports_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: true,
    shownAdd: true,
    shownAll: true,
  },
 
  {
    manager: "notification_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "thai_local_deposit_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: true,
    shownAdd: true,
    shownAll: true,
  },
 
 
  {
    manager: "settings",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "static_page_management",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "FAQ",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },

  {
    manager: "email_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
];

export default Permission;
