const Permission = [
  {
    manager: "dashboard",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "users_managers",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "subAdmin_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "interests_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "coins_pack_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "subscription_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "post_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "daily_rewards",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "country_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "global_setting",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "static_page_management",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
  {
    manager: "faq_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },

  {
    manager: "email_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownDelete: false,
    shownAdd: true,
  },
];

export default Permission;
