const Permission = [
  {
    manager: "user_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "transaction_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: false,
  },
  {
    manager: "subAdmin_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },
  // {
  //   manager: 'reports_manager',
  //   add: false,
  //   edit: false,
  //   view: false,
  //   shownView: true,
  //   shownAdd: true,
  //   shownAll: true
  // },

  {
    manager: "scratch_card_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },

  {
    manager: "notification_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },

  {
    manager: "settings",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "static_page_management",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "FAQ",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },

  {
    manager: "email_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "feedback_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },
  {
    manager: "report_manager",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: false,
    shownAll: false,
  },
  {
    manager: "reward_withdrawal_request",
    add: false,
    edit: false,
    view: false,
    shownView: true,
    shownAdd: true,
    shownAll: true,
  },
];

export default Permission;
